### ISSUE TITLE
Pash inconsistencies

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#129]
awk fails in the following scripts with the error: 
`awk: line 1: syntax error at or near == `
     
- evaluation/poets/scripts/bigrams_appear_twice.sh  
- evaluation/poets/scripts/find_anagrams.sh         
- evaluation/poets/scripts/vowel_sequencies_gr_1K.sh

the results between pash and bash are different for the script:  evaluation/poets/scripts/4letter_words.sh                

```
pash output:                                
    4767                                    
    4630                                    
    226                                     
    285                                     
bash output:                                
    9397                                    
    511                                     
```

**Comment by nvasilakis** [comment]
Can we test `awk` with single quotes too and confirm it's no longer a problem?
