### ISSUE TITLE
Self-contained benchmark setups

### ISSUE THREAD

**Issue by nvasilakis** [binpash/pash#135]
Currently, running benchmarks depends on `fetch.sh`. However, as the set of benchmarks grows, it becomes difficult to manage all dependencies through a single file: it is both impractical, as `fetch.sh` fetches all inputs even if it's just for running a single benchmark, and at times impossible, as some of the new benchmarks require a very complicated setup. My suggestion is to add an _idempotent_ `setup.sh` in each of the benchmarks, which would fetch all the necessary inputs (and other configurations, executables etc) for all the scripts in _that_ particular benchmark.

**Comment by angelhof** [comment]
Is this relevant as an issue in this repo? I am closing it since I feel like it isn't, but we could reopen if we want to have it here.
