### ISSUE TITLE
Cleanup parser directory

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#148]
Now that we use python binding for parsing, we could cleanup the parser directory to remove unnecessary installation files, ocaml files, etc...

**Comment by angelhof** [comment]
Actually the whole libdash (cloning it from github, installing it) is not needed. We should remove this.

**Comment by thurstond** [comment]
Parsing shell scripts to Pash AST does rely on the C portion of libdash - the Python script calls the C functions to get the initial parse, before processing it into the Pash AST

(the reverse direction - Pash AST to shell script - does not require libdash; it is pure Python)

**Comment by angelhof** [comment]
oh I see :) thanks for catching that

**Comment by angelhof** [comment]
@mgree is working on this!
