### ISSUE TITLE
What does the distribution story entail?

### ISSUE THREAD

**Issue by nvasilakis** [binpash/pash#24]
One of the key claims for an {O,N}SDI paper would be full distribution---including fs, runtime, and planner. Divide this to smaller tasks, and what it would take to complete them. 

From the README:

* Distributed file-system (and, more generally, networked distribution): as much of Unix is about files, incorporating an existing Unix-like distributed file-system is key to shell script distribution. With a DFS, /x/y would resolve to the filesystem of a specific node---but it should be location-aware so that Dish sends commands to where files (streams) reside.

* Planner: augment and extend the functionality of the planner with the ability to optimize the distributed script and map it efficiently on the underlying infrastructure---using information about the workload, infrastructure, etc. The planner should also add and leverage metadata (lines, batches etc.) for key planning decisions.

* Distributed runtime environment: currently Dish rewrites pipelines to extract parallelism---that is, the end result of our toolchain is still a shell pipeline. A more sophisticated runtime environment could provide significant benefits by manipulating metadata for both accelerating performance (e.g., wrapping commands with packing/unpacking) and fault tolerance (by knowing which of calls fail). It is important for the runtime to be optimized significantly so as to not have any issues.

**Comment by angelhof** [comment]
Closing since this is very old and obsolete.
