### ISSUE TITLE
Spell.sh inconsistency

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#260]
Is there any reason why [tests/spell.sh](https://github.com/andromeda/pash/blob/main/evaluation/tests/spell.sh) is different from  [oneliners/spell.sh](https://github.com/andromeda/pash/blob/main/evaluation/benchmarks/oneliners/spell.sh)?

**Comment by nvasilakis** [comment]
@angelhof Traditionally `spell.sh` had commands for skipping various classes of characters, like backspaces and things like that, and we tried to maintain that. 

@dkarnikis Isn't installing `iconv` part of the eval installation scripts?

**Comment by angelhof** [comment]
It doesn't fail because it isn't installed on my machine. It doesn't recognize the first character of the file, so the issue is slightly more complex (maybe not that much though 🙂).

**Comment by dkarnikis** [comment]
Well, If I remember correctly, I was the one that added the `iconv` part. I think that `iconv` was needed due to weird characters being read from the data (as Konstantinos mentioned). On my machine it was running correctly with and without iconv, but in one of the server machines, `iconv` was the only way to solve the issue.
