### ISSUE TITLE
New annotation class: file-parallel and read-only

### ISSUE THREAD

**Issue by nvasilakis** [binpash/pash#281]
Based on the discussions of the Annotations working group, we believe we will need a couple of new classes annotations for `non-parallelizable pure` and `side-effectful` commands. The first additional annotation would describe a subclass of `non-parallelizable pure` and `side-effectful` commands that are safe to parallelize across file boundaries (allowing parallelization of `for`, `xargs`, and other similar constructs). The second class would be `side-effectful` commands that only read environment variables—including hardware properties, `/proc` filesystem etc.

**Comment by angelhof** [comment]
Ported to: https://github.com/binpash/annotations/issues/12
