### ISSUE TITLE
Correctness tests fail

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#286]
Since the annotation commit 555c3eb4, `deadlock_test` and `shortest_scripts` tests (on compiler tests), fail to pass (different output).

This is my fault, since the CI was broken (I hope that I fixed it with the newest update).

Commit: 555c3eb4
Kernel: Linux livestar 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 GNU/Linux
OS: Debian GNU/Linux 9 (stretch)
Machine: Livestar

**Comment by angelhof** [comment]
Fixed by #292
