### ISSUE TITLE
Annotations can't capture high level functions

### ISSUE THREAD

**Issue by DanielSongShen** [binpash/pash#288]
The current annotation language cannot capture the classification of high level functions like `xargs`. 

For example, `$IN | xargs cat` applies the `cat` command on `$IN` and is hence stateless while `$IN | xargs ls` applies `ls` on `$IN` and is hence side-effectful.

**Comment by nvasilakis** [comment]
@DanielSongShen We're collecting annotation-related issues [in the relevant section of the README file](https://github.com/binpash/pash/tree/main/annotations#issues)! :-)
