### ISSUE TITLE
CI should not run on draft PRs

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#291]
@dkarnikis, @nvasilakis I think that CI should not be invoked in draft PRs, since they are supposed to be volatile, therefore leading to too many CI invocations. The DCO should probably be run though.

**Comment by nvasilakis** [comment]
Agreed!

**Comment by dkarnikis** [comment]
Thanks for the feedback! CI now does not execute on draft PR's unless they are ready for review! DCO runs regardless of the CI.
