### ISSUE TITLE
Autodelete branches on merge

### ISSUE THREAD

**Issue by janekb04** [binpash/pash#303]
Currently, there are 58 branches in PaSh. Many of them are left behind after closed pull requests (#301, #298, #297, #294, and many more). I think these branches should be deleted and only active branches should be left.
Fortunately, [there is an option](https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) that allows for automatically deleting branches on merge. Also, [they could be restored](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/deleting-and-restoring-branches-in-a-pull-request), if needed, anyway.
Using [this Python 2 script](https://github.com/simplesurance/utils/blob/master/git/stale_github_pr_branches.py), I composed a list 31 branches, that I think can be deleted apart from enabling the option to delete any future stale branches:
```
poets_fixes
pash-wsl
binbash-fixes
agg-ann-options-default
pash-ci-cd
web-index
dockerfiles
fix-tests
test-ann-agg
tr
performance-ci-trigger
improved-r-split
docker-docs
dgsh-buffer-size
poets_8.2_2
bash-c-escape-char-fix
ae-fixes
pure-par-annotation
round-split-final
news
poets-fixes
debian
python-fixes
safe-expansion-analysis
setup
dgsh-tee
icfp-fixes
future
deps-fix
icfp-deps
ci-fixes
```

**Comment by nvasilakis** [comment]
Thanks @janekb04! Speaking for myself here—I think that's a terrific idea! Will keep you updated..

**Comment by angelhof** [comment]
I think we can indeed safely close all PRs that were merged (because Github allows restoring them). There are some stale branches that never made it to `main` that I would prefer keeping for now though. 

I will enable the option to autodelete branches on PRs and I will delete all the branches that are left open.

**Comment by nvasilakis** [comment]
> branches that never made it to `main` that I would prefer keeping for now though.

+1
