### ISSUE TITLE
WSL instructions links are broken

### ISSUE THREAD

**Issue by mendhak** [binpash/pash#327]
Hi on the [tutorial page](https://binpa.sh/docs/tutorial/#installation), the link  

> For windows installation, follow this [guide](https://binpa.sh/docs/tutorial/windows.md).

leads to a 404. 

On the [Github tutorial](https://github.com/binpash/pash/blob/main/docs/tutorial/tutorial.md#windows-using-wsl) page, the link

> A short tutorial is included in the [contributing](https://github.com/binpash/pash/blob/main/docs/contrib) guide.

leads to a 404.

**Comment by dkarnikis** [comment]
Hello @mendhak!
Thank you for your feedback.

I have updated the website and created a new PR for the github 404 issue.

Thanks again!

**Comment by mendhak** [comment]
Excellent thanks both!
