### ISSUE TITLE
Please fix/drop Arch Linux installation support

### ISSUE THREAD

**Issue by fabiscafe** [binpash/pash#328]
Hello Everyone :wave: 

Currently the install script is pretty broken on Arch Linux.
* https://github.com/binpash/pash/blob/main/scripts/up.sh#L34
Checks for groups that don't exist on Arch. We dont have a default group that is allowed to use sudo. The user decides this by themself. So at this point there is no elegant way to check if there is sudo support in the system. Also if you install sudo later on, the user still needs to [set it up manually](https://wiki.archlinux.org/title/sudo#Configuration)

* https://github.com/binpash/pash/blob/main/scripts/up.sh#L36
Might be me being stupid but what is the point in checking if the user is in these groups and only run `bash distro-deps.sh` if the user is. And 2 lines down https://github.com/binpash/pash/blob/main/scripts/up.sh#L38 run it anyways?

* https://github.com/binpash/pash/blob/main/scripts/distro-deps.sh#L51
This is a no-go. -Sy in combination with -S will lead to a partial update https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported and the partial update is what it does 2 lines down https://github.com/binpash/pash/blob/main/scripts/distro-deps.sh#L53.

* https://github.com/binpash/pash/blob/main/scripts/distro-deps.sh#L53
Speaking of this line. pacman does have a function to skip the user confirmation request --noconfirm and there is no need to reinstall packages who are already installed --needed. For that part I'd suggest
```
   arch*) 
     echo "|-- running pacman install...."
     pacman -Syu git libtool m4 automake curl pkg-config python-pip libffi make autoconf gcc10 sudo inetutils bc --noconfirm --needed &> $LOG_DIR/pacman_update.log
     ;;
```
However this will not ultimately work, as you're not root at this point and pacman is unable to install anything as far as I can tell.

Sadly I don't have to much time to really dive into the structure of the whole installation to provide a MR or write a [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD). Maybe it would be the best option to even drop Arch entirely from the installation script support. If I haven't seen something important please let me know. thank you :+1:

**Comment by dkarnikis** [comment]
Hello @fabiscafe!
Thank you for your feedback.

You are right, we should definitely fix all the issues related to sudo access.
Do you think building a PKGBUILD would be a better alternative than the current installation process?

Thanks again

**Comment by fabiscafe** [comment]
@dkarnikis Sorry for the late response. For some reason github ends up in my spam folder 2/3 of the time :/
Thanks for this change already.
For the PKGBUILD, yes. If possible, a PKGBUILD would be the best option there is.

**Comment by dkarnikis** [comment]
@fabiscafe No problem at all :)
I am in the process of creating a PKGBUILD (I have tested it in native Arch and in an Arch container with no issues).
Could you take a look [here](https://aur.archlinux.org/packages/pash-shell/) and make some comments on it?

**Comment by fabiscafe** [comment]
Hi Thanks for the PKGBUILD already
[packager](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pash-shell#n6) is nothing you should set. because the packager is the person who builds it in the end, not the one who maintains the PKGBUILD.
The MIT license needs to be shipped and placed by you, since it's not a common license. It's explained here: https://wiki.archlinux.org/title/PKGBUILD#license

To get to the source. I'd recommend you to use let makepkg handle the stuff by themself. We usually handle it like this:
```
_commit=2b4db9ddb1616ce6fe56575724c966177bb950f7  # tags/v.04^0
source=("git+https://github.com/binpash/pash.git#commit=$_commit")
```
So you pull in directly the commit from a tag. This means you have a non changing source and so it's save to use. Instead a git tag is not fix and can be changed later on, which is why using the tag it self is no trustworthy.
This also makes you able to remove the prepare() content.

For the install part it's a bit more complicated. At first the echo is not necessary. People are fully aware of what they do, while they do that :stuck_out_tongue: 

The _scripts/setup-pash.sh_ might not be usable here as you install python dependencies via pip, that's something you shouldn't do as they will conflict with system python. 

- https://archlinux.org/packages/community/any/python-jsonpickle/
- https://archlinux.org/packages/community/x86_64/python-yaml/
- https://archlinux.org/packages/extra/x86_64/python-numpy/
- https://archlinux.org/packages/community/x86_64/python-matplotlib/

are available via main repos and should be set as makedepends (or depends if you need them at runtime).

for the package() part. We really should find a way to avoid 777 on root owned areas. It's a huge security hole that also might trigger the removal of the PKGBUILD at some point.
red and green as well as another echo should be removed too. The echo message doesn't matter to the packager here. That's something the user should know, and so should end up in the [INSTALL](https://wiki.archlinux.org/title/PKGBUILD#install) file.

Please wait a bit, I'll write later today (Just need to grab 1 or 2 coffee) a basic structure for this PKGBUILD. I think it's easier to move on from there. :smile:

**Comment by dkarnikis** [comment]
Thanks for all the feedback!
Feel free to send me a message in case you need any assistance on the building process or I can switch back to fixing it when I have spare time (my schedule is a bit tight currently).
I will definitely take into consideration all your tips for the next PKGBUILD!

**Comment by fabiscafe** [comment]
# PKGBUILD
```
# Maintainer: Dimitris Karnikis <dkarnikis@gmail.com>

pkgname="pash-shell"
_reponame="pash"
pkgver=4
pkgrel=1
pkgdesc="PaSh: Light-touch Data-Parallel Shell Processing"
url="https://binpa.sh/"
arch=("x86_64")
license=('MIT')
install=install
_commit=2b4db9ddb1616ce6fe56575724c966177bb950f7  # tags/v.04^0
source=("git+https://github.com/binpash/pash.git#commit=$_commit")
depends=('python-jsonpickle' 'python-yaml' 'python-numpy' 'python-matplotlib')
makedepends=('git' 'gcc' 'gcc10')
checkdepends=('inetutils')
sha256sums=('SKIP')

pkgver() {
    cd "${srcdir}/${_reponame}"
    git describe --tags | sed 's/v.//;s/^0*//;s/-/+/g'
}

prepare() {
    # Hardcode this in here, as we already know where it is placed and there is no need
    # for the user the set it later on
    sed -i 's|^export PASH_TOP=.*|export PASH_TOP="/opt/pash"|' "${srcdir}/${_reponame}/pa.sh"
}

build() {
    export PASH_TOP="${srcdir}/${_reponame}"

    cd ${PASH_TOP}
    git submodule init
    git submodule update

    cd compiler/parser
    make libdash

    cd "${PASH_TOP}/runtime"
    make
}

check() {
    cd "${PASH_TOP}"
    "${PASH_TOP}/evaluation/tests/input/setup.sh"
}

package() {
    cd "${srcdir}/${_reponame}"
    install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
    /usr/bin/install -dm755 "${pkgdir}/opt/pash"
    
    cp -r ./annotations ./compiler ./evaluation ./runtime "${pkgdir}/opt/pash/"
    /usr/bin/install -m755 ./pa.sh "${pkgdir}/opt/pash/pa.sh"
}
```
# install
```
post_install() {
  if [ -f /opt/pash/pa.sh ]
    then
      ln -s "/opt/pash/pa.sh" "/usr/bin/pa.sh"
  fi
}

pre_remove() {
  if [ -f "/usr/bin/pa.sh" ]
    then
      rm "/usr/bin/pa.sh"
  fi
}
```

I haven't tested it yet. It pushes me to the help if I try to run it and that's everything I did so far
![grafik](https://user-images.githubusercontent.com/18744080/136021145-d19e6131-78ad-4512-a285-9ad16d39ee84.png)

This however ships a lot of not necessary files as currently runtime components seems to be not split out on build time. see https://github.com/binpash/pash/issues/348
I do change the version 04 to 4, as 04 looks funny without purpose and 04 == 4 anyways. It also autogenerates the `pkgver` based on the git commit you put in the `_commit` var.

I do not use the install script at all, since it's more of a burden here. The same for `$PASH_TOP`. I hardcode it in pa.sh as I know where I do install it. This PKGBUILD will not set 777 to /opt as this is a big security hole. It will also use _/usr/bin/pa.sh_, instead of _/usr/local/bin_, because [local](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html#purpose24) is not meant for distro specific packages.

The _docs_ dir is not included. Usually they should end up in another **pash-shell-docs** package, but since they are markdown and do link to a lot of online documents anyways It might be better to just keep them in the git repo.

For a future release it would however be a LOT better if #348 was resolved, so we can actually have clean packages.

**Comment by fabiscafe** [comment]
# PKGBUILD with additional docs package
```
# Maintainer: Dimitris Karnikis <dkarnikis@gmail.com>

pkgbase="pash-shell"
pkgname=('pash-shell' 'pash-shell-docs')
_reponame="pash"
pkgver=4
pkgrel=1
pkgdesc="PaSh: Light-touch Data-Parallel Shell Processing"
url="https://binpa.sh/"
arch=("x86_64")
license=('MIT')
install=install
_commit=2b4db9ddb1616ce6fe56575724c966177bb950f7  # tags/v.04^0
source=("git+https://github.com/binpash/pash.git#commit=$_commit")
depends=('python-jsonpickle' 'python-yaml' 'python-numpy' 'python-matplotlib')
makedepends=('git' 'gcc' 'gcc10')
checkdepends=('inetutils')
sha256sums=('SKIP')

pkgver() {
    cd "${srcdir}/${_reponame}"
    git describe --tags | sed 's/v.//;s/^0*//;s/-/+/g'
}

prepare() {
    # Hardcode this in here, as we already know where it is placed and there is no need
    # for the user the set it later on
    sed -i 's|^export PASH_TOP=.*|export PASH_TOP="/opt/pash"|' "${srcdir}/${_reponame}/pa.sh"
}

build() {
    export PASH_TOP="${srcdir}/${_reponame}"

    cd ${PASH_TOP}
    git submodule init
    git submodule update

    cd compiler/parser
    make libdash

    cd "${PASH_TOP}/runtime"
    make
}

check() {
    cd "${PASH_TOP}"
    "${PASH_TOP}/evaluation/tests/input/setup.sh"
}

package_pash-shell() {

  cd "${srcdir}/${_reponame}"
  install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/pash-shell/LICENSE"
  /usr/bin/install -dm755 "${pkgdir}/opt/pash"

  mv ./annotations ./compiler ./evaluation ./runtime "${pkgdir}/opt/pash/"
  /usr/bin/install -m755 ./pa.sh "${pkgdir}/opt/pash/pa.sh"
}

package_pash-shell-docs() {
  pkgdesc="Documentation for PaSh"
  arch=("any")
  depends=()
  cd "${srcdir}/${_reponame}"
  /usr/bin/install -dm755 "${pkgdir}/opt/pash"
  mv ./docs "${pkgdir}/opt/pash/"
  install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/pash-shell-docs/LICENSE"
}
```

This one also builds a -docs package. install file from above stays the same.

**Comment by dkarnikis** [comment]
Wow. This is amazing work @fabiscafe!!
Super clean work. However, your name should be on the PKGBUILD as well, you did all the hard work and fixed all the issues.
However, I think that gcc10 should be dropped and switch to gcc (since it was an Ubuntu thing using older gcc version, whereas arch is rolling release). 
What do you think?

**Comment by dkarnikis** [comment]
Moreover, running `makepkg -si` i got this error:
```sh
ackages (8) cblas-3.10.0-1  python-cycler-0.10.0-8  python-kiwisolver-1.3.2-1
             qhull-2020.2-4  python-jsonpickle-1.5.2-1
             python-matplotlib-3.4.3-1  python-numpy-1.21.2-1
             python-yaml-5.4.1.1-2

Total Download Size:   11.30 MiB
Total Installed Size:  60.82 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 python-jsonpickl...    62.3 KiB  89.4 KiB/s 00:01 [######################] 100%
 python-yaml-5.4....   173.2 KiB  1237 KiB/s 00:00 [######################] 100%
 cblas-3.10.0-1-x...    35.8 KiB   215 KiB/s 00:00 [######################] 100%
 python-numpy-1.2...     4.8 MiB  12.6 MiB/s 00:00 [######################] 100%
 python-cycler-0....    12.6 KiB   119 KiB/s 00:00 [######################] 100%
 python-kiwisolve...    56.7 KiB   348 KiB/s 00:00 [######################] 100%
 qhull-2020.2-4-x...  1169.1 KiB  5.36 MiB/s 00:00 [######################] 100%
 python-matplotli...     5.0 MiB  12.1 MiB/s 00:00 [######################] 100%
 Total (8/8)            11.3 MiB  3.71 MiB/s 00:03 [######################] 100%
(8/8) checking keys in keyring                     [######################] 100%
(8/8) checking package integrity                   [######################] 100%
(8/8) loading package files                        [######################] 100%
(8/8) checking for file conflicts                  [######################] 100%
error: failed to commit transaction (conflicting files)
python-numpy: /usr/bin/f2py exists in filesystem
Errors occurred, no packages were upgraded.
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> python-jsonpickle
  -> python-yaml
  -> python-numpy
  -> python-matplotlib
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.

```

**Comment by fabiscafe** [comment]
https://github.com/binpash/pash/blob/main/runtime/agg/cpp/Makefile asks for gcc10 and it wont build with 11 (that is default for Arch right now). I've tried that:
```
make[1]: Entering directory '/build/pash-shell/src/pash/runtime/agg/cpp'
g++ -Wall -std=c++17 -O3 -DNDEBUG -Icommon common/main.cpp -Iaggregators/wc -o ./bin/wc
g++ -Wall -std=c++17 -O3 -DNDEBUG -Icommon common/main.cpp -Iaggregators/uniq -o ./bin/uniq
g++ -Wall -std=c++17 -O3 -DNDEBUG -Icommon common/main.cpp -Iaggregators/tr -o ./bin/tr
g++ -Wall -std=c++17 -O3 -DNDEBUG -Icommon common/main.cpp -Iaggregators/grep -o ./bin/grep
In file included from common/main.cpp:2:
aggregators/wc/agg.h: In function ‘void aggregate()’:
aggregators/wc/agg.h:19:27: error: ‘numeric_limits’ is not a member of ‘std’
   19 |     size_t padding = std::numeric_limits<size_t>::max();
      |                           ^~~~~~~~~~~~~~
aggregators/wc/agg.h:19:48: error: expected primary-expression before ‘>’ token
   19 |     size_t padding = std::numeric_limits<size_t>::max();
      |                                                ^
aggregators/wc/agg.h:19:51: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   19 |     size_t padding = std::numeric_limits<size_t>::max();
      |                                                   ^~~
      |                                                   std::max
In file included from /usr/include/c++/11.1.0/algorithm:62,
                 from aggregators/wc/agg.h:6,
                 from common/main.cpp:2:
/usr/include/c++/11.1.0/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make[1]: *** [Makefile:15: wc] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/pash-shell/src/pash/runtime/agg/cpp'
make: *** [Makefile:67: agg] Error 2
make: *** Waiting for unfinished jobs....
```
So I did it with gcc10 for now.

----

The reason you have this conflict is probably because you have installed python dependencies via pip, without a virtual environment and destroyed your pacman package management with that. This is the reason why we do not do that on Arch, but do exclusively use pacman to install dependencies.

**Comment by dkarnikis** [comment]
Ok great (rest in peace pacman). The gcc issue is solved in https://github.com/binpash/pash/pull/312 and will be added in a future release.
Could you also add your name and credentials in the PKGBUILD?

**Comment by dkarnikis** [comment]
Great work @fabiscafe . 
Thanks again for using PaSh. Your tips and assistance definitely helped us :)
If your are familiar with other packaging options (i.e., .deb), or want to contribute in general, feel free to do so!
I will update the PKGBUILD in the following days. 

PS: for the rest of the issues that you mentioned in first post, feel free to create a PR :)
