### ISSUE TITLE
Errors while trying to run unabashedly bash, as oposed to POSIX shell that is, scrpt

### ISSUE THREAD

**Issue by moosotc** [binpash/pash#340]
Trying to build https://github.com/moosotc/llpp/ yields 
```
- cd xsrc/llpp                    
- $PASH_TOP/pa.sh build.bash build
sh: 146: Syntax error: redirection unexpected
Traceback (most recent call last):
  File "/home/malc/x/rcs/git/pash/compiler/pash.py", line 142, in <module>
[...]
```

**Comment by dkarnikis** [comment]
Hello @moosotc.
Thank you for your feeback.

The [build.bash](https://github.com/moosotc/llpp/blob/master/build.bash) script you provided is using bash. 
In the current state of PaSh, we only support POSIX shell compliant scripts, where in contrast, bash scripts are not necessarily POSIX. For this reason, PaSh is not a drop-in replacement for bash, so the majority of scripts that execute on bash are not supported out of the box.

Furthermore, to verify that your script is not [POSIX compliant](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html) (check `POSIXLY_CORRECT` tag), you may use 
`set -o posix` in the top of build.bash. 
Running the script again with bash i get the following error:
```
dkarnikis@llpp:bash build.bash build
build.bash: line 147: syntax error near unexpected token `<'
build failed
```

Thank you again

**Comment by moosotc** [comment]
Dimitris Karnikis ***@***.***> writes:

> Hello @moosotc.
> Thank you for your feeback.
>
> The
> [build.bash](https://github.com/moosotc/llpp/blob/master/build.bash)
> script you provided is using bash.  In the current state of PaSh, we
> only support POSIX shell compliant scripts, where in contrast, bash
> scripts are not necessarily POSIX. For this reason, PaSh is not a
> drop-in replacement for bash, so the majority of scripts that execute
> on bash are not supported out of the box.
>
> Furthermore, to verify that your script is not [POSIX
> compliant](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html)
> (check `POSIXLY_CORRECT` tag), you may use `set -o posix` in the top
> of build.bash.  Running the script again with bash i get the following
> error: ``` ***@***.***:bash build.bash build build.bash: line 147:
> syntax error near unexpected token `<' build failed ```
>
> Thank you again

Thanks for the feedback. I know that bash is not POSIX sh, build.bash is
in bash because... reasons [1]... No shell i have, so far, used can
claim 100% compliance with relevant specifications. POSIXLY_CORRECT does
not bring bash in compliance ethier, to the best of my knowledge, there
are still quirks. It would have been nice for pash to specify which
interpeterns it aims to "compatible" with. In my experience, claiming be
"POSX Shell" compatibility is clamining compatibility with an empty set,
i.e. very hard to test.

**Comment by angelhof** [comment]
Hi @moosotc and thanks for using PaSh :)

To be precise, PaSh tries to be compatible with the POSIX-parseable fragment of bash. Namely, it tries to have the same behavior as bash, but cannot parse bash special syntax.

The technical reason behind this is that PaSh uses a POSIX-compliant parser (libdash) and therefore cannot parse bash specific constructs. However, it uses bash under the hood for executing the parallel versions of scripts and therefore should have very similar behavior to bash when it can parse the input script.

Let me know if you have any more questions.

**Comment by moosotc** [comment]
Konstantinos Kallas ***@***.***> writes:

> Hi @moosotc and thanks for using PaSh :)
>
> To be precise, PaSh tries to be compatible with the POSIX-parseable
> fragment of bash. Namely, it tries to have the same behavior as bash,
> but cannot parse bash special syntax.
>
> The technical reason behind this is that PaSh uses a POSIX-compliant
> parser (libdash) and therefore cannot parse bash specific
> constructs. However, it uses bash under the hood for executing the
> parallel versions of scripts and therefore should have very similar
> behavior to bash when it can parse the input script.

Thank you for an explanation!

>
> Let me know if you have any more questions.
>

One question, what in your opinion would be easier, to turn build.bash
into something pash parsable or somehow utilize GNU Parallel (or
something similar) to get me some of tha parallelism.

**Comment by angelhof** [comment]
> One question, what in your opinion would be easier, to turn build.bash
into something pash parsable or somehow utilize GNU Parallel (or
something similar) to get me some of tha parallelism.

I am afraid that both alternatives would require significant manual effort. In addition, I am not sure whether you could actually get significant parallelism for that script with either PaSh or GNU Parallel because it seems to depend on many custom commands and the parallelism can be extracted from loops and not input processing.

We are currently developing an extension for PaSh that extracts significant parallelism from for-loops but that is far from being ready.
