### ISSUE TITLE
Ubuntu docker gcc issue

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#351]
Due to [recent changes](https://github.com/binpash/pash/blob/3f5fcb7fefd05f92bebcfb5fd0848df7a05c4b3a/runtime/agg/cpp/Makefile#L7) in aggregators needing gcc10+ version to compile, the following command:
https://github.com/binpash/pash/blob/3f5fcb7fefd05f92bebcfb5fd0848df7a05c4b3a/scripts/distro-deps.sh#L31
fails to execute (due to missing `software-properties-common` package which is about ~70Mb). 
Can we do something about this without having to install this additional package?

**Comment by angelhof** [comment]
I think this is not relevant anymore (aggregators are in a different repo and not used)
