### ISSUE TITLE
Automate tasks on new PaSh releases

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#356]
Automate the following tasks when a new PaSh version is released:

- [x] Update docker containers
- [ ] Add a new github release
- [ ] Update packages for distros (currently, only Arch has a package)
- [x] Update the official website (for the moment, this has to be done manually)

I am quite positive, that the first three tasks can be automated using github actions.

**Comment by nvasilakis** [comment]
Great issue—I agree about the first three, and I can likely take care of automating most of the last task.

**Comment by dkarnikis** [comment]
Docker containers are updated automatically when a new update is merged with main branch regardless of the current PaSh version (Fedora 35 docker support is currently broken, waiting for a docker update to fix the issue). 

The next step would be to automatically generate a new github release when PaSh version gets updated

**Comment by angelhof** [comment]
I think that all of those are currently automated!
