### ISSUE TITLE
Python crash when running an empty file

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#363]
Sometimes, when providing an empty file as input to pash, python crashes with the following message:
```sh
Traceback (most recent call last):
  File "/home/dkarnikis/pash/./compiler/pash_runtime_daemon.py", line 97, in <module>
    main()
  File "/home/dkarnikis/pash/./compiler/pash_runtime_daemon.py", line 86, in main
    with open(args.input) as fin, open(args.output, "w") as fout:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pash_bEHtKAx//runtime_in_fifo_ReUd'
```
The same issue happens when running: `./pa.sh -c ' '` 
(I guess the behavior is the same since `-c` flag writes the given input to an output file and then forwards it to pash.) 

Reproduce:
```sh
touch empty_file
./pa.sh empty_file
```

Commit: 54209c8326544eef914ddabfd53ccac3ca56cfea
Kernel: 5.13.0-19-generic
OS: Ubuntu
Version: 21.10

I could not reproduce this issue on Arch Linux running Linux kernel 5.12.13-arch1-1.

**Comment by angelhof** [comment]
Does that still happen @dkarnikis ? If not, let's close
