### ISSUE TITLE
Pash execution hangs when giving empty input via -c flag

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#364]
When providing an empty input to pash, python execution hangs:

Reproduce:
` ./pa.sh -c ''`

Commit: 54209c8
Kernel: 5.13.0-19-generic
OS: Ubuntu
Version: 21.10

I can reproduce this issue on Arch Linux running Linux kernel 5.12.13-arch1-1.

**Comment by angelhof** [comment]
@dkarnikis still happening?

**Comment by dkarnikis** [comment]
I can still reproduce the bug on Ubuntu 18.04

**Comment by angelhof** [comment]
@dkarnikis should be addressed by #425. If it does (and tests pass) let's merge and close :)
