### ISSUE TITLE
Inconsistent behavior between bash and pash in string parsing

### ISSUE THREAD

**Issue by tammam1998** [binpash/pash#376]
When trying to run the following pipeline I need to make changes to the way strings are passed for pash for compilation to succeed

for bash to run I need to not have any quotation marks around things like $FILE or it would be interpreted as a string '$FILE'
```
ffmpeg -y -i $FILE -f mp3 -ab 192000 $OUT/$(basename $FILE .wav).mp3 > "$logname";
```
for pash to correctly compile I need to have the quotation marks or the compiler fails
```
ffmpeg -y -i '$FILE' -f mp3 -ab 192000 '$OUT'/'$(basename $FILE .wav).mp3' > "$logname";
```

**Comment by tammam1998** [comment]
Similarly if I replace $logname with $OUT/$(basename $FILE .wav).log compilation fails unless I use '$OUT'/'$(basename $FILE .wav).log'

**Comment by angelhof** [comment]
Thanks, I will take a look!
