### ISSUE TITLE
Output redirection using &> not working correctly

### ISSUE THREAD

**Issue by tammam1998** [binpash/pash#379]
The following code has a different behavior between bash and pash
```
func() {
    echo hi
}

func &> log.txt
```

In bash, the output would be written to log.txt while using pash the output is written to stdout

**Comment by angelhof** [comment]
It doesn't redirect correctly indeed. I will work on it, however, for now you could use `>` instead of `&>`.

**Comment by angelhof** [comment]
Dash seems to behave the same way as PaSh so it must have to do with parsing! 

```sh
$ rm -f log.txt; bash test.sh; echo "---"; cat log.txt
---
hi
$ rm -f log.txt; sh test.sh; echo "---"; cat log.txt
hi
---
$ rm -f log.txt; ./pa.sh test.sh; echo "---"; cat log.txt
hi
---
```
