### ISSUE TITLE
Pash not running on Debian

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#381]
Executing any command with PaSh hangs during execution.

Reproduce:
`
$PASH_TOP/pa.sh -c 'echo test'
`

will neither print nor close PaSh.
Even running `$PASH_TOP/pa.sh --help` will not exit (however, it will print the usage log message).
By setting `pash_daemon=0` in pa.sh seems to be a temp fix (for me at least).

Commit: ea6c3a642c131094436b34d57e3719c66b9489d6
Branch: future
Kernel:  Linux livestar 4.9.0-16-amd64 #1 SMP Debian 4.9.272-1 (2021-06-21) x86_64 GNU/Linux
OS: Debian GNU/Linux 9 (stretch)
Machine: Livestar

**Comment by angelhof** [comment]
This probably has to do with the latest changes. Now the pash `daemon` communicates through sockets. I suspect that this is either a problem with some usage of `nc` (in `compiler/pash_init_setup.sh`) or the inability of the daemon to bind and listen on the socket. Could you use `-d 1` and tell me what happens?

BTW, using `--no_daemon` flag will have the same behavior as setting that flag manually.

**Comment by dkarnikis** [comment]
```sh
│Daemon:  WARNING: Could not parse annotation for file: /home/dkarnikis/fpash/annotations/pr.json
│Daemon:  |-- Expecting property name enclosed in double quotes: line 14 column 18 (char 285)
│Daemon:  SocketManager: Made sure that socket does not exist
│Daemon:  SocketManager: Created socket
│Daemon:  SocketManager: Successfully bound to socket
│Daemon:  SocketManager: Listenting on socket
│Daemon:  Received data:
│Daemon:  Received data:
│Daemon:  Received data:
```
and several more `Daemon:  Received data:`

**Comment by angelhof** [comment]
It seems to me then that this might be a problem with `nc`. 

This function https://github.com/binpash/pash/blob/future/compiler/pash_init_setup.sh#L185 is called in `pa.sh`. Could you modify it to not send it stdout and stderr to `/dev/null` and instead print it out for debugging?

**Comment by dkarnikis** [comment]
```sh
nc: unix connect failed: No such file or directory
nc: unix connect failed: No such file or directory
nc: unix connect failed: No such file or directory
nc: unix connect failed: No such file or directory
nc: unix connect failed: No such file or directory
nc: unix connect failed: No such file or directory
nc: unix connect failed: No such file or directory
nc: unix connect failed: No such file or directory
Daemon:  WARNING: Could not parse annotation for file: /home/dkarnikis/fpash/annotations/pr.json
Daemon:  |-- Expecting property name enclosed in double quotes: line 14 column 18 (char 285)
Daemon:  SocketManager: Made sure that socket does not exist
Daemon:  SocketManager: Created socket
Daemon:  SocketManager: Successfully bound to socket
Daemon:  SocketManager: Listenting on socket
Daemon:  Received data:
```

**Comment by angelhof** [comment]
Does it manage to exit this waiting loop ever?

**Comment by dkarnikis** [comment]
No it doesn't :/

**Comment by angelhof** [comment]
I am not sure how to debug this. You can check and echo the status of each `nc` after it executes, as well as read the manpage to see if some of the flags that I use does not exist in the version of `nc` in this distribution.

**Comment by angelhof** [comment]
@dkarnikis if it is fixed, let's close this :)
