### ISSUE TITLE
Catch SIGINT in the parallel script and kill children

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#40]
At the moment when debugging a parallel script, if we kill it using SIGINT, then all of its spawned background processes stay alive and this might lead to inconsistent results (due to commands waiting to read and write to pipes).

We should catch the sigint in the output script and kill all the children processes. This could happen in the backend that could output a signal handler in the output parallel script (see https://stackoverflow.com/questions/2618403/how-to-kill-all-subprocesses-of-shell on how to kill).

**Comment by asharma0703** [comment]
This can be closed, it's addressed by #458. Tested by interrupting `./pa.sh background-process.sh` where `background-process.sh` looks like
```
#!/bin/bash
sleep 60 &
sleep 60
```

**Comment by angelhof** [comment]
Thanks!
