### ISSUE TITLE
Issue on unix50 with pash

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#400]
When running the unix50 benchmark using pash without any flags (using run_all_benchmarks.sh), the 20.sh file is executed (i can see the output log with the correct result), however, the execution time it took is never printed on the screen (performed the benchmark test twice and if I execute it manually, I have no such issue).
I am not quite sure if this can be labeled as a bug though.

**Comment by angelhof** [comment]
I will take a look, thanks

**Comment by dkarnikis** [comment]
Same issue applies with 34.sh.
If I pkill (eager.sh and 34.sh) I get the timers

**Comment by angelhof** [comment]
Do they finish executing when they don't print the time? Or do they keep being alive? It might be the case that we are not cleaning up everything properly.

**Comment by dkarnikis** [comment]
I don't think they finish, since there are still processes running with the respective script names (even though the results are already written to the files)

**Comment by angelhof** [comment]
Thanks, that is helpful info I think.

**Comment by angelhof** [comment]
Surprisingly, on my machine they work 🥲. I will have to investigate on the machine that this happens (is it `deathstar` or `livestar`)?

**Comment by dkarnikis** [comment]
I don't remember at all, I have to check it.

**Comment by dkarnikis** [comment]
I don't know what I was thinking on my last comment. It applies to both of the machines.
Moreover, max-temp has the same behavior (I have to kill a pending `cat` process without arguments to get the time).
Still, the output with bash/pash is the same

**Comment by angelhof** [comment]
OK I will have to explore that on the machines, thanks for the info.

**Comment by angelhof** [comment]
20.sh works for me on livestar. Could you investigate if my recent changes make a difference?
