### ISSUE TITLE
run.par.sh time bug

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#409]
When running the evaluation scripts (using run.par.sh), the execution time is not printed in the respective files (neither in the `script_name.par.time` nor at par.res). The timer however is printed in the `stdout`.

**Comment by dkarnikis** [comment]
Moreover, in case where output is printed to the `stderr` from a script (i.e., `comm: file 2 is not in sorted order`), the execution time will not be written in the `stdout`! (When using bash, the timer is printed correctly to the `stdout` even with the error)

**Comment by angelhof** [comment]
I am on it!
