### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by valuta1995** [binpash/pash#434]
While following the instructions on docker from source I came across a few problems.

- On the line `docker build -t "pash/18.04" .` I need to add the `-f` flag with the path to the Dockerfile (`./docker/ubuntu/Dockerfile`)
- There is no `/pash` in the docker container, there however is `/opt/pash`
- pa.sh does not run in the container as it cannot find pexpect. The workaround I used is to remove the `usr/local/lib/python3.6/dist-packages` folders from python_pkgs and place their content in the python_pkgs folder.
- Before the previous step and after, running pa.sh gives the following error:

```
Error: Maximum retries: 100 exceeded when waiting for daemon to bind to socket!
```

**Comment by valuta1995** [comment]
I made two pull requests for the doc changes. I will not touch the folder structure as I'm unsure as to how to do that properly (without messing other parts up).

**Comment by dkarnikis** [comment]
Hey @valuta1995 . Thank you for your feedback and your PRs. Could you try signing your commits with: 
`git commit -s -m 'git message'` to pass the DCO test?
You may find additional information [here](https://github.com/binpash/pash/pull/435/checks?check_run_id=4817077894) for the #435 PR

**Comment by valuta1995** [comment]
I used the editor on github, which does not play well with DCO, so I made a new request through cli.

**Comment by angelhof** [comment]
Hi @valuta1995! Thanks a lot for letting us know of these issues. Me and @dkarnikis will try to debug maximum retry error as soon as possible. We are drowning in work though so it might take a few days!

**Comment by angelhof** [comment]
This PR #439 should address the maximum retries issue. We will try to automatically fix the python_pkg issue in the next few days but for now you should be good to go.

**Comment by valuta1995** [comment]
To quickly verify I installed netcat-openbsd (`sudo apt install netcat-openbsd`) manually in the container. This worked. Thank you for your help!

**Comment by dkarnikis** [comment]
#440 Should fix the python_pkg issue. Could you verify if it works for you as well?
