### ISSUE TITLE
Potential redundancy in Dockerfile and distro-deps.sh

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#438]
Do we need both the separate dockerfiles for each distro, and the case analysis in distro-deps? Could we get away with having one Dockerfile and only checking in `distro-deps.sh`?

**Comment by dkarnikis** [comment]
I think the case-analysis in distro-deps is required  whether we are using docker or not.
Moreover, these images are prebuilt and available [`here`](https://hub.docker.com/repository/docker/binpash/pash).

So, I suppose we could try removing(?)  the dockerfiles for debian and fedora from the repo, and updating the correct documents. Should I proceed with that?

**Comment by angelhof** [comment]
That sounds good. If they are indeed not useful, we could try to delete the unnecessary dockerfiles. But probably this is not a priority.

**Comment by dkarnikis** [comment]
In [dockerhub](https://hub.docker.com/r/binpash/pash), we have several references to these dockerfiles in the repo.  Should I remove these as wel?

**Comment by angelhof** [comment]
I think I misexpressed my point. My point was simply that both `distro-deps.sh` and the dockerfiles, have partly the same functionality. So I am confused why we need both. Our dockerfiles only call some shell commands, so couldn't they just use `distro-deps.sh`? And then we can have 3 dockerfiles, but all of them just call distro-deps and do nothing else.
