### ISSUE TITLE
Pash tests fail

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#441]
* evaluation/tests/interface_tests/output/test10_distr.time      
bash ouput:
```
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
127
1
```

pash out:
```
1
```

* evaluation/tests/interface_tests/output/test14_distr.time      
bash out:
```
value1 value2
value1 value2
```
pash out:
```
value1 value2
```

* evaluation/tests/interface_tests/output/test_set_e_3_distr.time
bash out:
```
passed pipeline
passed elif
passed compound-brace
passed compound-for
passed compound-if
passed compound-while
passed compound-until
```

pash out:
```
passed pipeline
```

* evaluation/tests/interface_tests/output/test_set_e_distr.time  p
bash out:
```
passed while
passed until
passed if
passed AND list
passed OR list
passed AND-OR list
passed negated pipeline
```

pash out:
```
passed while
```

* evaluation/tests/results/tr-test_2_distr_--r_split --dgsh_tee --parallel_pipelines --profile_driven.time 
pash-w2 output
```
43145,2831824d43144
< ﻿
< The
< Project
< Gutenberg
< EBook
< of
< War
< and
< Peace,
```
                               
* evaluation/tests/results/tr-test_8_distr_--r_split --dgsh_tee --parallel_pipelines --profile_driven.time 
pash-w8 output
```
21573,2831824d21572
< ﻿
< the project gutenberg ebook of war and peace, by leo tolstoy
< 
< this ebook is for the use of anyone anywhere at no cost and with almost
< no restrictions whatsoever. you may copy it, give it away or re-use
< it under the terms of the project gutenberg license included with this
< ebook or online at www.gutenberg.org
< 
< 
```

Branch: main [9e345f5366cc3afbae664755171cebf2fc210a9b]
Kernel: Linux 5.13.0-25-generic
OS: Ubuntu 21.10 LTS (Impish Indri)
Machine: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz

**Comment by angelhof** [comment]
In general have we ever tested on ubuntu 21? It probably has to do with utilities being uninstalled or having different versions. I think we need to be very clear with which OS versions we support and have CI run tests on all of the ones that we clearly want to support. @dkarnikis this might require a longer investigation.
