### ISSUE TITLE
Temp Analytics error

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#443]
When running temp-analytics.sh with `--dgsh_tee --parallel_pipelines --profile_driven` (blish_no_comm), 
I get the following error on deathstar:
```sh
executing max temp with pash Thu 20 Jan 2022 07:15:35 AM EST
temp-analytics.sh:                                          
gzip: stdin: invalid compressed data--format violated       
(23) Failed writing body 
(23) Failed writing body 
(23) Failed writing body                                    
....
(23) Failed writing body

gzip: stdin: invalid compressed data--format violated
(23) Failed writing body
(23) Failed writing body
(23) Failed writing body
(23) Failed writing body
874.265
```
I don't have the same issue when running other flag configurations.
Running on branch future

**Comment by angelhof** [comment]
Could you try rerunning it with all subsets of 2 out of 3 of these flags and see if it fails for those too? Also running it with the addition of `--r_split` too? I am not sure why this would be an issue with this exact flag combination.

**Comment by dkarnikis** [comment]
Running with the following configurations, I think the bug is related to `r_split`:
```
export PASH_FLAGS="--r_split --dgsh_tee --parallel_pipelines --profile_driven"
421.258
export PASH_FLAGS="--r_split --dgsh_tee --parallel_pipelines"
428.272
export PASH_FLAGS="--r_split --dgsh_tee"
616.152
export PASH_FLAGS="--dgsh_tee"
error
export PASH_FLAGS="--dgsh_tee --parallel_pipelines --profile_driven"
error
export PASH_FLAGS="--dgsh_tee --parallel_pipelines"
error
export PASH_FLAGS=" "
1278
```

**Comment by angelhof** [comment]
Hmm, so it seems to be that having dgsh-tee without r-split creates a problem. @tammam1998 could you investigate this?
