### ISSUE TITLE
Move modified dgsh-tee to the binpash org

### ISSUE THREAD

**Issue by nvasilakis** [binpash/pash#448]
Some of the PaSh setup scripts pull from @tammam1998's `dgsh-tee` clone repo. Could we please move this repo under the binpash organization and update the setup scripts accordingly? Thanks!

**Comment by dkarnikis** [comment]
Fixed at https://github.com/binpash/pash/pull/442/commits/91e76a30259a4e99a82a06dbb078c6964ac43015
