### ISSUE TITLE
Add special flag for compiling C++ aggregators

### ISSUE THREAD

**Issue by nvasilakis** [binpash/pash#449]
The new, highly optimized C++ aggregators require a special build environment that a user might not want to prepare (or be unable to prepare, due to `sudo`). Could we make this an option for the setup scripts, like `--opt-agg` or `--optimized-aggregators`? If this flag is _not_ used, PaSh should use the default aggregators; if this flag is used, the script should confirm the availability of the build environment and notify the user accordingly.

**Comment by janekb04** [comment]
@nvasilakis Before `distro-deps.sh` was changed in #310 ([diff here](https://github.com/binpash/pash/pull/310/files#diff-35d17ed8a8e43ec4306806e5feae0813a17e649dc9dfe2249ecb437906eed433)), it had already contained `sudo` commands. The aggregator PR only expanded the list of the installed components.

**Comment by nvasilakis** [comment]
Yes, you're right @janekb04 ! Part of the goal in the small change outlined in this issue is to ensure anyone can run `setup-pash.sh` even in environments where they don't have `sudo` access. This is due to a recent complication during a demo, where setup proved more difficult than it should have been!

**Comment by janekb04** [comment]
Thanks for the clarification @nvasilakis . What I meant by my comment is that, as far as I understood the contents of `distro-deps.sh`, there are other components in PaSh that also require `sudo` access apart from aggregators. As such, I am not sure if the option should be called `--opt-agg`. Maybe a name like `--no-sudo` would be more fitting?

**Comment by janekb04** [comment]
I also saw that packages installed include `curl` and `python`. Assuming that they are not already present, PaSh installation without `sudo` access wouldn't be possible anyway.

**Comment by nvasilakis** [comment]
Exactly!`distro-deps.sh` requires `sudo` (to install all system-level dependencies, including hopefully the C++ compiler) and `setup-pash.sh` does not (to only compile and set PaSh up). I am referring to the second, which should always fall back to an installable path with minimal dependencies (for quick demos, talks, and such).

(Discussion around `distro-deps.sh` is in #451)

**Comment by angelhof** [comment]
> Maybe a name like --no-sudo would be more fitting?

I will contribute my 2 cents even though noone asked for them :) Since the C++ aggregators are not a critical dependency of PaSh, I think that it would be better to have them compiled optionally (using a flag `--opt-agg`). If there are other dependencies that are not critical, e.g., `pyplot`, we should also move those behind an installation flag, maybe `--full-install` would be a good name?

**Comment by nvasilakis** [comment]
> If there are other dependencies that are not critical, e.g., `pyplot`, we should also move those behind an installation flag, maybe --full-install would be a good name?

Adding this to the discussion of `distro-deps.sh` (which is the `sudo`-relevant script)  in #451.

**Comment by janekb04** [comment]
It seems to me like there are actually two issues here. One issue is about installing optional dependencies and the second one is about requiring `sudo`. 
Using a name like `--no-sudo` would say when the option should be used (when one has no `sudo` access), but not what the option does. One could infer that it omits installing something, but there would need to be some documentation, that would have to be maintained, to say what the option does.
On the other hand `--full-install` does say what it does (install all components), but it doesn't communicate what the prerequisites are (`sudo` access). Also, some optional components could require `sudo` access, while others could have other requirements (for example, no `sudo` access, but still an internet connection).
Maybe the best choice would be to provide an option for each component. Like `--libdash=enable --pyplot=disable --aggregators=auto`. Where `auto` would install a component if that is possible (for example, it would detect if the user has `sudo` access automatically). Additionally a master option could be provided, like `--install-all-optional` and `--install-only-required`.

**Comment by nvasilakis** [comment]
The `sudo` is really not relevant here (not sure why @angelhof  is responding to that): When we split the scripts, we moved all of `sudo` commands outside of `setup-pash.sh`. Your other suggestion, @janekb04, about options and optional dependencies (for both scripts) sounds like a great idea!

**Comment by dkarnikis** [comment]
Addressed in https://github.com/binpash/pash/pull/463
