### ISSUE TITLE
Only 26/54 test cases pass when running  compiler/test_evaluation_scripts on docker

### ISSUE THREAD

**Issue by tammam1998** [binpash/pash#475]
To reproduce

- run 'docker run -it binpash/pash:debian-10 /bin/bash'
- `cd compiler`
- `./test_evalutation_scripts.sh

I believe this issue is related to PR #445 where we removed some of the env variables, specifically the following:
```
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_COLLATE C
```

**Comment by dkarnikis** [comment]
Thanks!
I will work on that

**Comment by dkarnikis** [comment]
addressed in https://github.com/binpash/pash/pull/476
