### ISSUE TITLE
Issue when parallelizing commands with multiple inputs

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#48]
Parallelizing commands that have multiple inputs (such as `comm -23`) needs to ensure that the non-parallelized (and thus duplicated input) is not a pipe but a file.

Example:
```sh
cat in1 in2 | comm -23 - in3

should not become:

comm -23 in1 in3 | cat pipe1 &
comm -23 in2 in3 | cat pipe2 &
cat pipe1 pipe2 

if in3 is a pipe
```

This is a low priority issue to deal with after OSDI. It would require some analysis (or a materialization of the pipe) as file to make this correct.

**Comment by nvasilakis** [comment]
(We might be able to close this, as `tee` is in.)

**Comment by angelhof** [comment]
But the issue is still not totally solved so I suggest keeping it open. I need to do some more investigation on `comm` to see if it works.

**Comment by angelhof** [comment]
`comm` still has issues, so in order to close this we need to find a command that has configuration input to properly test the functionality.

**Comment by angelhof** [comment]
This is solved now (see the `spell-grep` test in `evaluation/tests`).
