### ISSUE TITLE
Fix agg tests

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#499]
Fix all broken tests named [fix-test-*](https://github.com/binpash/pash/tree/main/evaluation/tests/agg) to have the same behavior both on bash and pash (must also work on the latest pash distro/debian)

**Comment by angelhof** [comment]
We need to move aggregators in their own repo (and ideally run their tests there).

At the moment we are not using them here, and separating them would enable improving them/working on them separately than the rest of the PaSh project.

**Comment by nvasilakis** [comment]
Agreed!

**Comment by angelhof** [comment]
Aggregators have moved to https://github.com/binpash/aggregators!
