### ISSUE TITLE
Generating figures 9 and 10 from the paper: PaSh: Light-touch Data-Parallel Shell Processing

### ISSUE THREAD

**Issue by nos111** [binpash/pash#510]
Hi all,

I'm trying to generate figures 9 and 10 from the paper. I ran the evaluation script listed in /pash/evaluation/eval_script/run_all
The script had multiple issues like those web index errors:

```
executing web index Fri Mar 25 01:31:04 UTC 2022
web-index.sh: cat: '/home/nour/pash/evaluation/benchmarks/web-index/input/./en/articles/'$'\343\201\240''/_/_/'$'\343\201\240''.html': No such file or directory cat: '/home/nour/pash/evaluation/benchmarks/web-index/input/./en/articles/'$'\343\201\240''/'$'\343\201\243''/'$'\343\201\246''/User_talk~'$'\343\201\240\343\201\243\343\201\246\343\201\260\343\202\210''.html': No such file or directory cat: '/home/nour/pash/evaluation/benchmarks/web-index/input/./en/articles/'$'\343\201\240''/'$'\343\202\213''/'$'\343\201\276''/'$'\343\201\240\343\202\213\343\201\276''.html': No such file or directory cat: '/home/nour/pash/evaluation/benchmarks/web-index/input/./en/articles/'$'\343\201\275''/_/_/'$'\343\201\275''.html': No such file or directory cat: '/home/nour/pash/evaluation/benchmarks/web-index/input/./en/articles/'$'\343\201\275''/'$'\343\201\210''/'$'\343\201\223''/User~'$'\343\201\275\343\201\210\343\201\223''.html': No such file or directory cat: '/home/nour/pash/evaluation/benchmarks/web-index/input/./en/articles/'$'\351\276\241''/_/_/'$'\351\276\241''.html': No such file or directory cat: '/home/nour/pash/evaluation/benchmarks/web-index/input/./en/articles/'$'\342\221\210''/_/_/'$'\342\221\210''.html': No such file or directory 
```

The rest of the tests worked and ran for around 20 hours and I used the gen_data.sh script to generate the final.csv and the script had the following errors:

```
run1.tmp
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
run2.tmp
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
run3.tmp
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted.....
```

I used the generate_charts.R script to generate the graphs but they are very different from the ones listed in the paper. Is there a way to generate the exact same graphs as the paper? I saw that the script that was used to generate them was moved to evaluation/other and I haven't had any luck making it generate the plots.

**Comment by nvasilakis** [comment]
Hi @nos111! Could you please provide a bit more information about (1) which paper you're talking about (there are quite a few PaSh-related papers), (2) the details of the platform you're using, (3) the sequence of commands you tried?

(Also, feel free to use blocks to help us distinguish between commands/code/output and the rest of the text — thank you!)

**Comment by nos111** [comment]
@nvasilakis Hi Nikos,
Thanks for the fast reply.

(1) The paper is: PaSh: Light-touch Data-Parallel Shell Processing

(2) the details of the platform you're using: 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal


(3) the sequence of commands you tried?
`sudo curl up.pash.ndr.md | sh
export PASH_TOP=/home/nour/pash
export PATH=$PATH:$PASH_TOP
chmod +x $PASH_TOP/evaluation/benchmarks/web-index/input/install-deps.sh
$PASH_TOP/evaluation/benchmarks/web-index/input/install-deps.sh
chmod +x $PASH_TOP/evaluation/benchmarks/dependency_untangling/input/install-deps.sh
$PASH_TOP/evaluation/benchmarks/dependency_untangling/input/install-deps.sh
sudo apt update -qq
sudo apt-get install -y nodejs
sudo apt install --no-install-recommends software-properties-common dirmngr
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
sudo apt install --no-install-recommends r-base
sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
sudo apt install --no-install-recommends r-cran-rstan
sudo R
#install.packages('ggplot2', dep = TRUE)
cd /pash/evaluation/eval_script
./run_all.sh
`

Afterwards I used the following commands to generate the plots:
`./gen_data.sh
./generate_charts.R final.csv
`

The plots that were generated are boxplots instead of the trendlines in figure 9 and the speedup in figure 10.

**Comment by nvasilakis** [comment]
Thank you! The best way to reproduce these results would be to use the [frozen `eurosys-2021` branch (and release)](https://github.com/binpash/pash/releases/tag/eurosys-2021). All these should still work (but might require re-building that version of PaSh.)

Since then, however, PaSh [has evolved quite a bit](https://nikos.vasilak.is/p/pash:osdi:2022.pdf) to achieve significantly better performance and compatibility — making some of the EuroSys21 evaluation scripts (mostly) irrelevant today.

**Comment by nos111** [comment]
Going to give to try that branch.

Thank you so much Nikos :)

**Comment by nos111** [comment]
I have managed to generate the figures from the branch you mentioned @nvasilakis. Thanks for the help :)
