### ISSUE TITLE
pash log file is empty

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#529]
Reproduce:
```sh
cd $PASH_TOP/evaluation/intro
time $PASH_TOP/pa.sh -w 8 --log_file pash.log demo-spell.sh > pash-spell.out
# pash.log is empty
cat pash.log
```
I think this can be 'fixed' by adding `--debug 1` as argument.
Is this intended?

**Comment by angelhof** [comment]
Yes, the log_file on its own doesn't include anything without debug. It might be sensible to let the user know that without debug, this file doesn't include anything, but it shouldn't be a priority I think!
