### ISSUE TITLE
Flag `--assert_compiler_success` lets `pa.sh` get stuck

### ISSUE THREAD

**Issue by festutz** [binpash/pash#530]
Without the flag, everything is fine. Sure the compilation fails but it executes the sequential version.
With the flag, `pa.sh` gets stuck and never returns:
![image](https://user-images.githubusercontent.com/29564651/163458033-a603e775-9ad3-48f8-b73e-d7969afd53e9.png)
The log-file indicates that an Exception was caught but I guess `pa.sh` shall still return at some point.

**Comment by angelhof** [comment]
Which branch are you running on? On `future` this doesn't get stuck for me. Could you let me know of the branch, and also copy the logfile (`log.txt`) here?
