### ISSUE TITLE
ann-agg test fails with autosplit

### ISSUE THREAD

**Issue by tammam1998** [binpash/pash#538]
When running the test_evaluation_script the ann-agg test case fails when no flags are used, specifically it fails when auto-split mode is used instead of r_split.  

I ran it individually I got the following error
`
Traceback (most recent call last):
  File "/home/tammam/pash/runtime/agg/py/cat.py", line 2, in <module>
    import sys, os, functools, utils
  File "/home/tammam/pash/runtime/agg/py/utils.py", line 51
    print 'echo "one\\ntwo\\nthree" > 1.t'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('echo "one\\ntwo\\nthree" > 1.t')?
`

**Comment by angelhof** [comment]
It is not relevant anymore since we will not be using auto_split
