### ISSUE TITLE
binpash/pash:latest (and installation in general) does not include graphviz

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#540]
The latest docker container does not include graphviz.

@dkarnikis when you have some time, could you respond to the following?

Is the `binpash/pash` image updated everytime there is a commit to `main`? Or is it everytime there is a release?  I will add the graphviz installation as a PR, but we need to make sure that binpash/pash is also updated. :)

**Comment by dkarnikis** [comment]
The docker images are updated when a new release is issued. https://github.com/binpash/pash/blob/main/.github/workflows/docker.yaml and https://github.com/binpash/pash/blob/main/.github/workflows/ghcr.yaml could be modified to push new images when pushing on main

**Comment by angelhof** [comment]
Thanks a lot!!!
