### ISSUE TITLE
Update pash version before new releases

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#545]
We are on 0.7.1, however the main repo version is on 0.7 ([file](https://github.com/binpash/pash/blob/3694a61034eeb77b145cb9dc4399b9a593dd7bbc/compiler/config.py#L13)). 

This also affects the website building scripts (they parse the `config.py` file to grep the version)

**Comment by angelhof** [comment]
Thanks, I noticed that too! I am planning to make a guide on how to make new releases and add all the instructions there.
