### ISSUE TITLE
Exclamation marks in string literal output get escaped

### ISSUE THREAD

**Issue by bhaible** [binpash/pash#572]
This shell script `hello.sh`
```
#!/bin/sh
echo "Hello world!"
```
prints
```
Hello world!
```

When executed with pash:
```
$ ./pash/pa.sh hello.sh
Hello world\!
```

As you can see, there is an extra backslash in the output.

**Comment by angelhof** [comment]
Thanks for reporting this, we fixed tihs in PR #574, which was now merged in the `future` branch.
