### ISSUE TITLE
Unnecessary "!" escape

### ISSUE THREAD

**Issue by asharma0703** [binpash/pash#610]
```
$ bash -c 'echo "!"'
!
$ ./pa.sh -c 'echo "!"'
\!
```

Removing "!" from [`chars_to_escape` in ast2shell.py](https://github.com/binpash/pash/blob/main/compiler/parser/ceda/ast2shell.py#L335) fixes it and passes interface tests, but not sure if that's actually safe/valid beyond existing tests.

**Comment by angelhof** [comment]
Thanks! I think this is solved in `future` (soon to be merged on main) with PR #574

**Comment by angelhof** [comment]
Also merged this to `main` now! Closing this issue but feel free to reopen if the problem persists.
