### ISSUE TITLE
Remove flag `--r_split`

### ISSUE THREAD

**Issue by festutz** [binpash/pash#625]
With the new annotations framework, we prioritize round robin over the previous standard parallelization (aka consecutive chunks parallelization). In contrast to before, both types of parallelization might be used (for different command invocations). Thus, the flag `--r_split` is pointless and can be removed.

NOTE: this shall only be addressed once https://github.com/binpash/pash/pull/623 has been merged to `future`.

**Comment by angelhof** [comment]
Fixed in #640
