### ISSUE TITLE
Connect aggregators with PaSh

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#71]
Currently some aggregators are hard coded in PaSh. Make this architecture more general so that they can be discovered and new ones can be added. This would require some new annotation and a way to create nodes in the IR with the aggregator code.

**Comment by angelhof** [comment]
@nvasilakis We can use this PR to track integrating aggregators into annotations. (After #280)

Regarding the aggregator per command or per predicate, I think that both could work, but the second feels more natural, as it decouples the categorization of a command given its arguments (predicate) from the actual action (command class, aggregator). If we go with the first alternative, then the aggregator should duplicate this categorization logic to figure out how it has been invoked. In addition, an aggregator for a command that sometimes is side-effectful and sometimes pure does not make so much sense IMO.

**Comment by nvasilakis** [comment]
@angelhof Agreed. The second alternative will also depend on the (eventual) expressive power of predicates, which is something that's somewhat unclear now.

We are [collecting issues around annotations](https://github.com/binpash/pash/tree/main/annotations#issues) so we should soon have a better understanding of the landscape and needs from  aggregators.

**Comment by angelhof** [comment]
This is now solved with the new PRs.
