### ISSUE TITLE
Improve on dependencies during installation

### ISSUE THREAD

**Issue by nvasilakis** [binpash/pash#73]
There are two major possibilities for improvement.

1. Improve compatibility with broader versions of Python. In many systems, it's very difficult to get the dependencies right . For example, in older versions of Ubuntu it requires adding the ppa from `deadsnakes`, and when running `pip` on some machines we get:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
```

2. Somehow minimize dependency on the entire OCaml toolchain. As above, currently we often requires installing a new, different version  of the `ocaml` compiler, which sometimes is not available in the `apt` repos by default and requires adding the ppa from `avsm`. Additionally. this process takes several minutes (about 8 minutes on an older desktop workstation). If we could somehow make this more widely available or use what's provided with `opam` we might be able to improve here.

**Comment by thurstond** [comment]
In terms of 2) removing OCaml, the C ports of the OCaml libdash code already achieve this:

- shell script to JSON (uncommon cases will be fixed in a few days): https://github.com/andromeda/pash/blob/ceda/compiler/parser/ceda/parse_to_json2.c
- JSON to shell script: https://github.com/andromeda/pash/blob/ceda/compiler/parser/ceda/json_to_shell2.c

(There are nice optimizations to be had by skipping JSON, but that's a separate issue.)

**Comment by angelhof** [comment]
That's great, can they just be used in place of `parse_to_json.native` and `json_to_shell.native`? If so, I can try to replace them in PaSh, make sure that all tests pass as expected, and then merge these changes.

**Comment by thurstond** [comment]
parse_to_json2 needs a few days' work; json_to_shell2 is ready, right now, as a drop-in replacement for json_to_shell.native.

The steps to get it working in PaSH are:

1. install json-c v0.15 (step-by-step instructions at https://github.com/andromeda/pash/blob/ceda/compiler/parser/ceda/README.md, though I think installing it globally also works)
2. compile json_to_shell2 (Makefile provided in the ceda/ directory)
3. change config.py:
`PRINTER_BINARY = os.path.join(PASH_TOP, "compiler/parser/ceda/json_to_shell2")`
4. profit

When running `./test_evaluation_scripts.sh` on my docker instance, 192/192 tests pass.

**Comment by angelhof** [comment]
I think this is solved!
