### ISSUE TITLE
Fix Padding Inconsistencies in wc.py

### ISSUE THREAD

**Issue by guptaa47** [binpash/pash#96]
Currently the wc command assumes a fixed padding of 7 characters. Unfortunately commands like `wc -l` require no padding. This would require dynamic calculation of padding.

**Comment by nvasilakis** [comment]
Great point. Additionally, these commands work slightly differently on Linux vs, say, OS X, which affects these details:-)

**Comment by angelhof** [comment]
This is relevant for the annotation repo so closing for now
