### ISSUE TITLE
Move all logs to user-specific directory, rather than /tmp

### ISSUE THREAD

**Issue by nvasilakis** [binpash/pash#97]
Currently, Pash writes all logs and intermediate files to `/tmp`. This causes a problem when many different users attempt to use PaSh on the same computer — the common case in shared large-scale multiprocessors. One idea would be to quickly change all `/tmp` pointers to some `$HOME`-local directory. A better option would be to pair this with a `pash --init` flag that is used to set up Pash.

(Additionally, jobs could be given IDs so that they do not mess up with each other when multiple invocations of PaSh operate in concurrently.)

**Comment by angelhof** [comment]
Addressed since logs are written in invocation specific pash direcotry.
